name: php-composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Install Composer
      run: composer install
    
#     - name: Run phpstan on Controller
#       run: vendor/bin/phpstan analyse app
      
    - name: Run phpstan on Views
      run: vendor/bin/phpstan analyse app/views

    - name: PHPUnit Login Testing
      run: php vendor/bin/phpunit tests/LoginTest.php

    - name: PHPUnit Cart Testing
      run: php vendor/bin/phpunit tests/CartTest.php

    - name: PHP MD Account Controller (Design)
      run: vendor/bin/phpmd app/controllers/AccountController.php xml rulesets/design.xml

    - name: PHP MD Admin Controller (Clean Code)
      run: vendor/bin/phpmd app/controllers/AdminController.php xml rulesets/cleancode.xml

    - name: PHP MD Baby Registry Controller (Naming)
      run: vendor/bin/phpmd app/controllers/BabyRegistryController.php xml rulesets/naming.xml
      
    - name: PHP MD Default Controller (Unused Code)
      run: vendor/bin/phpmd app/controllers/DefaultController.php xml rulesets/unusedcode.xml

    - name: PHP MD Product Controller (Clean Code)
      run: vendor/bin/phpmd app/controllers/ProductController.php xml rulesets/cleancode.xml

    - name: PHP MD Shop Controller (Naming)
      run: vendor/bin/phpmd app/controllers/ShopController.php xml rulesets/naming.xml

    
